apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: echo-server-release
spec:
  releaseName: echo-server
  serviceAccountName: tenant-admin
  driftDetection:
    mode: enabled
  install:
    remediation:
      retries: -1
  interval: 1m
  chart:
    spec:
      chart: echo-server
      version: 0.5.0
      sourceRef:
        kind: HelmRepository
        name: echo-server-helmrepo
      interval: 12h
  values:
    image:
      tag: 0.9.2
    podSecurityContext:
      fsGroup: 3857
      runAsGroup: 3857
      runAsUser: 3857

    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
      readOnlyRootFilesystem: true
      runAsNonRoot: true
      seccompProfile:
        type: RuntimeDefault

    service:
      port: 8080

    application:
      logs:
        ignore:
          ping: true
