repos:
  - repo: https://github.com/eidp/actions-common
    rev: v1.3.0
    hooks:
      - id: generate-action-docs

  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
      - id: codespell
        exclude: 'dist/.*'
